### ISSUE TITLE
Enhancement : Create a News list using b̶o̶o̶k̶s̶h̶e̶l̶v̶e̶s̶ method

### ISSUE THREAD

**Issue by hydro-headlines** [hydro-headlines/hydro-headlines.github.io#1]
- [x] ~Add a bookshelves of book~

- [x] Each book is a issue of certain date

- [x]  On click redirect to the respective issue display

**Comment by Criticalcarpet** [comment]
Fixed/Added in https://github.com/hydro-headlines/hydro-headlines.github.io/commit/31f4a2b47d7d82b5e05184ab37534505dba301e1
